version: '3.8'
services:
  nextcloud:
    image: nextcloud
    networks:
      - main_default
    volumes:
      - ./nextcloud:/var/www/html
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.rule=Host(`yourdoamin`)"
        - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == manager
networks:
  main_default:
    external: true
    name: main_default
